# Generated by Django 5.1.1 on 2024-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(auto_created=True)),
                ('title', models.CharField(max_length=222)),
                ('name', models.CharField(max_length=222)),
                ('lavozim', models.CharField(max_length=222)),
            ],
        ),
    ]
