# Generated by Django 5.1.1 on 2024-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.TextField(),
        ),
    ]
